load ../../../code/semantics/interpreter-symbolic.maude
load ../../model/drones/Drones4_rendezvous_Instance#.maude

mod TEST-DRONE4-SYSTEM is
  including DRONES4_RENDEZVOUS_INSTANCE-MODEL-SYMBOLIC .
  including SPECIFICATION-LANGUAGE-SEMANTICS .

  op initConst : -> BoolExp .
  eq initConst = [true] .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(initial)) .
endm

mod TESTER is
  including TEST-DRONE4-SYSTEM .

  eq @m@ = ['DRONES4_RENDEZVOUS_INSTANCE-MODEL-SYMBOLIC] .
  eq MFlag = TFTF .
endm
