#!/bin/bash
#SBATCH -J analysis_test
#SBATCH -o ./log/result.o%j
#SBATCH -e ./log/result.e%j
#SBATCH -N 1
#SBATCH --ntasks=36
#SBATCH --ntasks-per-node=36

TESTER=tester

if [ "$1" -eq 2 ]; then
     cd ./t2-symVSdist
     bash $TESTER 
elif [ "$1" -eq 3 ]; then
     cd ./t3-mergeVSnon
     bash $TESTER $2
elif [ "$1" -eq 1 ]; then
     cd ./t1-symVSrand
     bash $TESTER 
fi
